# Copyright 2023 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI Backend CQL

on:
  pull_request:
    paths:
    - 'docs/**'
    - '.github/workflows/ci-docs.yml'
    - '.github/ISSUE_TEMPLATE/**'
    - 'requirements.txt'
    - 'docs.Dockerfile'
    - '*.md'

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - module: cql
            args: "-Pcassandra3-byteordered -Dtest=\"**/diskstorage/cql/*\""
            name: byteordered-diskstorage
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur -Dtest=\"**/diskstorage/cql/*\""
            name: murmur-diskstorage
            java: 8
          - module: cql
            args: "-Pcassandra3-byteordered -Dtest=\"**/graphdb/cql/*\""
            name: byteordered-graphdb
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur -Dtest=\"**/graphdb/cql/*\""
            name: murmur-graphdb
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur -Dtest=\"**/hadoop/*\""
            name: murmur-hadoop
            java: 8
          - module: cql
            args: "-Pcassandra3-byteordered -Dtest=\"**/core/cql/*\""
            name: byteordered-core
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur -Dtest=\"**/core/cql/*\""
            name: murmur-core
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur-ssl -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
            name: murmur-ssl
            java: 8
          - module: cql
            args: "-Pcassandra3-murmur-client-auth -Dtest=\"**/diskstorage/cql/CQLStoreTest.java\""
            name: murmur-client-auth
            java: 8
          - module: cql
            install-args: "-Pjava-11"
            args: "-Pcassandra3-murmur -Pjava-11 -Dtest=\"**/diskstorage/cql/*\""
            name: murmur-diskstorage-java-11
            java: 11
          - module: cql
            install-args: "-Pjava-11"
            args: "-Pcassandra3-murmur -Pjava-11 -Dtest=\"**/graphdb/cql/*\""
            name: murmur-graphdb-java-11
            java: 11
          - module: cql
            install-args: "-Pjava-11"
            args: "-Pcassandra3-murmur -Pjava-11 -Dtest=\"**/hadoop/*\""
            name: murmur-hadoop-java-11
            java: 11
          - module: cql
            args: "-Pscylladb -Dtest=\"**/diskstorage/cql/*\""
            name: scylladb-diskstorage
            java: 8
          - module: cql
            args: "-Pscylladb -Dtest=\"**/graphdb/cql/*\""
            name: scylladb-graphdb
            java: 8
          # FIXME: this takes forever to run
          # - module: cql
          #   args: "-Pscylladb -Dtest=\"**/hadoop/*\""
          #   name: scylladb-hadoop
          #   java: 8
          - module: cql
            args: "-Pscylladb -Dtest=\"**/core/cql/*\""
            name: scylladb-core
            java: 8
    steps:
      - run: 'echo "No build required"'
